[package]
name = "DofStaticCollectible"
edition = "2024.beta"
license = "Cascade DOL 1.0"
authors = ["Cascade Foundation (dos@cascade.foundation)"]

[dependencies]
BlobUtils = { git = "https://github.com/studio-mirai/blob_utils.git", rev = "mainnet" }
DosCollection = { git = "https://github.com/CascadeFoundation/dos_collection.git", rev = "mainnet" }
DosStaticCollectible = { git = "https://github.com/CascadeFoundation/dos_static_collectible.git", rev = "mainnet" }

[addresses]
dof_static_collectible = "0x0"

# DosStaticCollectible
# DosCollection
# DofStaticCollectible
